"""
Finalizer Agent - Compiles the complete research report
"""

from typing import Dict, Any
from langchain_core.messages import AIMessage


def finalizer_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """Final step: Compile the complete research report"""
    print("📋 Finalizing research report...")

    topic = state["topic"]
    formatted_content = state["formatted_content"]
    validation_results = state["validation_results"]
    sources = state["sources"]

    final_report = f"""
# Research Report: {topic}

## Executive Summary
{formatted_content.get('summary', 'No summary available')}

## Detailed Research
{formatted_content.get('detailed', 'No detailed content available')}

## Investment Opportunities
{formatted_content.get('investment', 'No investment opportunities identified')}

## Validation Report
{validation_results.get('report', 'No validation available')}

## Sources
{chr(10).join(f"- {source}" for source in sources) if sources else "No sources listed"}

## Validation Status
- Confidence Score: {validation_results.get('confidence_score', 'N/A')}/10
- Issues Found: {len(state.get('validation_issues', []))}
- Validation Date: {validation_results.get('timestamp', 'N/A')}

---
*Report generated by Multi-Agent Research System*
"""

    return {
        "final_output": final_report,
        "messages": state["messages"] + [AIMessage(content="Research report completed")]
    }
